### PR TITLE
React 15

### PR DESCRIPTION
**Pull request by eatyourgreens**
Upgrades the React packages to 15.3 and removes `defaultValue` from the editor.

### CODE REVIEW

**Comment by eatyourgreens** [comment]
This should be merged as part of zooniverse/Panoptes-Front-End#2984 to keep the React versions in synch.

**Comment by srallen** [comment]
Cool. I'm taking a look at both PRs this morning.

**Comment by rogerhutchings** [comment]
LGTM - I'll leave the PR open, as it'll need a version bump as well

**Comment by rogerhutchings** [comment]
Merging now, as there's a version bump as part of #48

**Comment by eatyourgreens** [comment]
Will this be broken now?
https://github.com/zooniverse/Panoptes-Front-End/pull/2984/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R17

**Pull request merged**
