### PR TITLE
Transpile and refactor

### LINKED ISSUE #32: transpile to es5 and point package.json to use it
We should transpile the source to es5 and update the package.json to use it and include it here. This is a barrier with setting up webpack with Panoptes Front End (and any other front end clients we may want to use webpack and this package) and we shouldn't expect clients to transpile package dependencies. Webpack can be setup to specifically transpile a package in the node_modules folder, but this is long term bad practice.

### PR DESCRIPTION
**Pull request by parrish**
Closes #32 

Generally cleans things up.  Some notable changes:

- removes zuul and gulp
- adds eslint
- transpiles the library when publishing

Run `npm version` to test, build, and pubish the new version.

Staged in PFE at https://update-markdownz.pfe-preview.zooniverse.org

### CODE REVIEW

**Comment by parrish** [comment]
Sorry for the larger PR.  It's mostly just tidying linter errors (whitespace, semicolons, syntax, etc) in c3ecb07.

**Comment by parrish** [comment]
Thanks!

**Comment by amyrebecca** [comment]
Are we going to need to update the package in NPM too? I eyeballed the changes and nothing seemed terrifying to me either.

**Comment by parrish** [comment]
Just a new publish -- the version step handles it.  PFE has a PR to switch to this in zooniverse/panoptes-front-end#3304

**Pull request merged**
