### PR TITLE
Update packages and fix footnotes

### PR DESCRIPTION
**Pull request by parrish**
Fixes zooniverse/Panoptes-Front-End#3001

- Upgrades dependencies
- Accepts or provides a unique document id for rendering context
- Captures the footnote link targets and prevents the page-rerender

I'm not thrilled with [`#captureFootnoteLinks`](https://github.com/zooniverse/markdownz/pull/42/files#diff-28d17d74c7dea151776bfc1698904d28R59), but it seems to pretty much be the only way to prevent anchor links from just reloading the page.

### CODE REVIEW

**Comment by parrish** [comment]
By the way, if you want to test this in PFE, I had some trouble at first.  Normally I either symlink or `npm link` the library in.  For whatever reason, I had to update PFE's package.json to specify `"markdownz": "file:/some/path/to/markdownz",` and `npm install` to get it to work right.  Probably something to do with babel/es6/etc.

**Comment by eatyourgreens** [comment]
zooniverse/Panoptes-Front-End#3000 fixed links to document fragments, so you shouldn't need to override links. 

IIRC `scrollIntoView` isn't supported by all browsers anyway.

**Comment by parrish** [comment]
zooniverse/Panoptes-Front-End#3000 still reloads the page content and [scrollIntoView](http://caniuse.com/#feat=scrollintoview) is well supported.

**Comment by eatyourgreens** [comment]
Ah, right. The footnote links in https://www.zooniverse.org/talk/13/18624?comment=164687 don't reload the page for me in Chrome, but I do see a bunch of network activity in Firefox.

I'm looking at fixing links in markdown and History more generally,  to fix the page zooming bug that's been annoying volunteers. https://github.com/zooniverse/Panoptes-Front-End/pull/2976#issuecomment-245300125 Hoping to have a PR up today or tomorrow.

**Comment by eatyourgreens** [comment]
Here you go zooniverse/Panoptes-Front-End#3021

**Comment by parrish** [comment]
Just tried this out against zooniverse/Panoptes-Front-End#3021

Turns out that if I don't use `#captureFootnoteLinks`, the anchor links break since the page re-renders and the target id changes.

**Comment by srallen** [comment]
With NPM's peer dependency deprecation for version 3, this might be a good opportunity to move babelify into `devDependencies` and remove the peer dependencies entirely. Thoughts?

**Comment by parrish** [comment]
Yep.  Had been thinking about that -- it's updated.

**Pull request merged**
