### PR TITLE
Install react packages as dev dependencies

### PR DESCRIPTION
**Pull request by eatyourgreens**
Move react, react-dom and prop-types to dev dependencies.

### CODE REVIEW

**Comment by eatyourgreens** [comment]
I think this will stop Markdownz from installing React 15 when the parent project is using React 16.

**Comment by eatyourgreens** [comment]
Should zooniverse/modal-form use peer dependencies too? We've not declared them before.

**Comment by srallen** [comment]
I think they might be a better way to go for long term maintenance. I had the same thought as you that they were deprecated, but I learned from the grommet team that they are not, just the auto-install part was deprecated.

**Comment by eatyourgreens** [comment]
Would something like
```json
peerDependencies: {
 react: ">= 15.6"
}
```
include all versions since 15.6, including 16?

**Comment by srallen** [comment]
Hm, I'm not sure if that would include 16. The grommet source uses an `||` to specify the React 15 and 16 ranges they support: https://github.com/grommet/grommet/blob/master/package.json#L27

**Comment by eatyourgreens** [comment]
Published as 7.6.0.

**Pull request merged**
