### PR TITLE
Render output with rehype-react

### PR DESCRIPTION
**Pull request by eatyourgreens**
Remove `dangerouslySetInnerHTML`. Render the HTML output with `rehype-react`.

### CODE REVIEW

**Comment by eatyourgreens** [comment]
This works in PFE. 👍

**Comment by goplayoutside3** [comment]
For documentation, what was the reason behind adding `rehype` here? 
___

Linking some related comments: 
Comment in FEM PR [5253](https://github.com/zooniverse/front-end-monorepo/pull/5352) asking about `dangerouslySetInnerHTML`: https://github.com/zooniverse/front-end-monorepo/pull/5352#pullrequestreview-1695493716

Comment in FEM PR [5253](https://github.com/zooniverse/front-end-monorepo/pull/5352) explaining that `utils.getHTML(markdown)` now sanitises the output HTML string with DOMPurify, before it's passed to Rehype in FEM's Markdownz component.

**Comment by eatyourgreens** [comment]
>For documentation, what was the reason behind adding rehype here?

To replace `dangerouslySetInnerHTML` with React `children` here:
https://github.com/zooniverse/markdownz/blob/8bc941ba2226081dd69b736839626941c95d5482/src/components/markdown.jsx#L52-L56

The `Markdown` component now renders a React component tree, rather than HTML strings.

**Comment by eatyourgreens** [comment]
I've added an example in #216, showing how you can safely render markdown as JSX.

**Comment by goplayoutside3** [comment]
Cool, thank you!

**Pull request merged**
